# Generated by Django 5.2.6 on 2025-10-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_location_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.AddField(
            model_name='location',
            name='upvoteCount',
            field=models.IntegerField(default=0),
        ),
    ]
