# Generated by Django 5.2.6 on 2025-10-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_location_address_location_upvotecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
