# Generated by Django 5.2.6 on 2025-10-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('amenity', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('upvoteCount', models.IntegerField(default=0)),
            ],
        ),
    ]
