# Generated by Django 4.2.25 on 2025-11-09 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_contactattempt_roommateprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roommateprofile",
            name="age",
        ),
        migrations.RemoveField(
            model_name="roommateprofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="roommateprofile",
            name="is_looking",
        ),
        migrations.RemoveField(
            model_name="roommateprofile",
            name="max_budget",
        ),
        migrations.RemoveField(
            model_name="roommateprofile",
            name="preferred_neighbourhoods",
        ),
        migrations.RemoveField(
            model_name="roommateprofile",
            name="race",
        ),
        migrations.RemoveField(
            model_name="roommateprofile",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="roommateprofile",
            name="age_range",
            field=models.CharField(
                choices=[
                    ("18-24", "18-24 years"),
                    ("25-34", "25-34 years"),
                    ("35-44", "35-44 years"),
                    ("45+", "45+ years"),
                ],
                default="25-34",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="roommateprofile",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="roommateprofile",
            name="display_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="roommateprofile",
            name="lifestyle",
            field=models.CharField(
                choices=[
                    ("early_bird", "Early Bird"),
                    ("night_owl", "Night Owl"),
                    ("flexible", "Flexible"),
                ],
                default="flexible",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="roommateprofile",
            name="neighbourhoods_csv",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of preferred neighborhoods",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="roommateprofile",
            name="occupation",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("working", "Working Professional"),
                    ("other", "Other"),
                ],
                default="working",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="roommateprofile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other / Prefer not to say"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="roommateprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
