# Generated by Django 4.2.25 on 2025-11-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_roommateprofile_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roommateprofile",
            name="is_looking",
            field=models.BooleanField(default=True),
        ),
    ]
