# Generated by Django 4.2.25 on 2025-11-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_roommateprofile_is_looking"),
    ]

    operations = [
        migrations.AddField(
            model_name="roommateprofile",
            name="race",
            field=models.CharField(
                choices=[
                    ("-", "No preference / Prefer not to say"),
                    ("chinese", "Chinese"),
                    ("malay", "Malay"),
                    ("indian", "Indian"),
                    ("other", "Other"),
                ],
                default="-",
                max_length=10,
            ),
        ),
    ]
